[Paths]
# Carpetas principales del sistema
base_folder = data
upload_folder = videos_test
result_folder = projects

[Video]
# Configuración del motor de extracción
# Intervalo de extracción en segundos
frame_interval = 1

#numero max de intentos para analizar un frame
max_intents_frame = 3

# Resolución de optimización para no saturar la RAM de los modelos locales
resize_width = 640
resize_height = 360