[Paths]
# Carpetas principales del sistema
datasets_folder = datasets
projects_folder = projects
config_folder = configs

[Video]
# Configuración del motor de extracción
# Intervalo de extracción en segundos
frame_interval = 5
frames_per_batch = 1

# Número max de intentos para analizar un frame en caso de fallo del modelo
max_intents_frame = 2

# Resolución de optimización para no saturar la RAM de los modelos locales
resize_width = 640
resize_height = 360

[Configuracion]
# Selección dinámica de prompts
selected_vlm_prompts_list = vlm_instructions

#seleccion del tipo de formato de respuesta del modelo
output_parser_type=text

#FUNCIONALIDAD DE DETECCION DE EVENTOS
#prompt seleccionado para el tipo de procesamiento especifico
batch_sys_prompt =modo_eficiencia_batch_ingles
temporal_sys_prompt=modo_ventana_temporal_ingles

#seleccion de algoritmo de postprocesado 
normalizer_algorithm=sliding_window

#FUNCIONALIDAD DE LOGICA DE RESUMENES
#prompt para la funcionalidad de logica de resumenes
llm_instructions = llm_instructions
semantic_sys_prompt = sys_prompt_1
descrip_per_batch = 3



