[Paths]
# Carpetas principales del sistema
datasets_folder = datasets
projects_folder = projects
config_folder = configs

[Video]
# Configuración del motor de extracción
# Intervalo de extracción en segundos
frame_interval = 1

# Número max de intentos para analizar un frame en caso de fallo de la IA
max_intents_frame = 3

# Resolución de optimización para no saturar la RAM de los modelos locales
resize_width = 640
resize_height = 360

[Configuracion]
# Selección dinámica de prompts
selected_vlm_prompts_list = vlm_instructions
selected_sys_prompt = sys_prompt_2